# required sudo permission
language: generic
sudo: required
services:
  - docker

# some series of set up before we deploy or run test
before_install:
  - docker build -t diracmmd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true diracmmd/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-183094109419"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY